### ISSUE TITLE
vglrun: no space left on device

### ISSUE THREAD

**Issue by logic-coder** [VirtualGL/virtualgl#208] opened 2022-08-09 05:26 UTC
I have had this problem many times, system is centos 7.x, nvidia RTX 4000 driver version is 470.x; 
Reboot the system to restore normal，but it won't take long for it to reappear.

I have tried different versions of VirtualGL.

**Comment by dcommander** [comment] 2022-08-09 09:23
Which version of VirtualGL are you using?  What 3D application are you running?  What arguments are you passing to the 3D application, if any?  What non-default VirtualGL settings are you using, if any?  What is your 2D X server configuration?  (For instance, are you using the VGL Transport with a client-side X server, or are you using the X11 Transport with an X proxy?  If you are using an X proxy, which one?)

No one else is experiencing this problem, so I need to know as much detail as possible so I can attempt to reproduce it.  I cannot fix it unless I can reproduce it.

**Comment by logic-coder** [comment] 2022-08-09 10:45
I have tried VirtualGL  2.6.3 and 3.0.1 with default VirtualGL settings, Usually a vnc desktop is started，and start glxgears in the desktop session；
I use "vglrun glxgears" to start the application on localhost without proxy mode.
Recurrence of the problem sometimes takes several hours，or it may be a few days.
The desktop window manager is xfce4.
Only one 3D application cannot reappear, multiple instances need to be started(>30).

**Comment by dcommander** [comment] 2022-08-09 13:47
Can you clarify what you mean by "Only one 3D application cannot reappear, multiple instances need to be started(>30)"?  Does the issue only occur when many instances are running?  If so, then it is probably due to X11 resource exhaustion, which is not surprising given that you are using the same X server as both a 3D X server and a 2D X server.  Note that VirtualGL is not useful in that case.  VirtualGL is only useful if the 2D X server does not have GPU-accelerated OpenGL, as is the case with X proxies, or if the 2D X server is not on the same machine as the application.

**Comment by logic-coder** [comment] 2022-08-10 02:39
Thank you for your reply, I sure the problem occurs only when many instances are running. But I have observed that the nvidia  video memory is not used much with nvidia-smi,.
I running 3D application on DISPLAY:100，so VirtualGL is useful for GPU-accelerated OpenGL.
How can I be sure that X11 resource exhaustion? 
Does it work if I change the Linux system shared memory size?

**Comment by dcommander** [comment] 2022-08-10 14:15
It is still very unclear how your system is configured. What is X display :100? What (and where) specifically are your 2D and 3D X servers? Your message above implied that you were not using an X proxy (you said “without proxy mode”), but the use of Display :100 implies that you are. GLXgears will not use very much GPU memory, so the fact that its usage doesn’t show up in nvidia-smi is normal. But the processes should at least show up.

**Comment by 892768447** [comment] 2022-08-19 11:20
maybe /dev/shm has no space
like this: 
```shell
root@test:/dev/shm# truncate -s 100G test4
truncate: failed to truncate 'test4' at 107374182400 bytes: No space left on device
```

**Comment by dcommander** [comment] 2022-08-19 12:57
Closing due to lack of information, as the OP has not provided sufficient details to aid in diagnosis.

**Closed by dcommander** 2022-08-19 12:57 UTC
