### ISSUE TITLE
[Question] Mouse very slow on sddm (Plasma KDE display and login manager)

### ISSUE THREAD

**Issue by aanno** [VirtualGL/virtualgl#245] opened 2024-02-08 12:03 UTC
After enabling virtualgl on Fedora 39 (with nvidia driver), I encounter a _very_ slow mouse on the sddm login screen. After login, the mouse is 'normal' and responsive, but on sddm it is hardly usable.

If I disable virtualgl, the problem is gone. The problem exists with either (GLX + EGL) or (EGL) alone. 

Any idea how to avoid the problem?

**Comment by dcommander** [comment] 2024-02-08 14:03
I will try to reproduce it. SDDM isn't commonly used with VirtualGL.

**Comment by dcommander** [comment] 2024-02-28 17:44
I unfortunately can't repro the issue, but I also don't have access to a Fedora machine with an nVidia GPU.  (The best I could do was either Rocky Linux 8 with an nVidia GPU or Fedora 39 with VMWare.)  If the issue occurs even when configuring VirtualGL for use only with the EGL back end, then it is likely an issue with the framebuffer device permissions.  If the issue occurs only if you restrict framebuffer device access to the vglusers group, then maybe the user under which the display manager is running needs to be added to the vglusers group.  If the issue occurs even if framebuffer device access is open to all users of the machine, then I have no clue.

**Comment by dcommander** [comment] 2024-07-19 16:28
Closing due to inability to reproduce and no further information provided by the poster

**Closed by dcommander** 2024-07-19 16:28 UTC
Labels: works for me
