### ISSUE TITLE
Different rendering results with vglrun -c proxy and vglrun -c rgb

### ISSUE THREAD

**Issue by ppira** [VirtualGL/virtualgl#117] opened 2020-02-04 07:16 UTC
When running a bit of code that renders an object on a transparent background I get different results when running it directly on a X11-proxy (vglrun -c proxy) vs running it with vglrun -c rgb (when vglconnected to another host).

Code sample: https://github.com/ppira/samples/blob/master/x11argb_opengl.c

Expected results: An opaque cube on a transparent background.
Results with vglrun -c rgb: A semi-transparent cube on a transparent background.

Is this a bug or am I just doing it wrong?

**Comment by dcommander** [comment] 2020-02-13 00:35
It's not a bug so much as it is a limitation.  Unfortunately, neither of the current compression/encoding methods supported by the VGL Transport (JPEG and RGB) can handle alpha channel information.  It would be necessary to extend the VGL Transport with a new encoding method (RGBA) in order to support that, and/or to extend libjpeg-turbo to support YCbCrA JPEG images, which would require supporting JPEG XT Part 9 (https://github.com/libjpeg-turbo/libjpeg-turbo/issues/232).  At the moment, the lack of alpha channel support in the VGL Transport means that your program displays incorrectly (with JPEG compression, it displays as all opaque.)  Bearing in mind that the VGL Transport was designed in 2003 as a bolt-on technology for remote X, there were no compositing X11 applications or window managers at the time.  Thus, the VGL Transport assumed (and still assumes) that the rendered OpenGL pixels will be pre-composited, and it ignores the alpha channel when reading back and encoding those pixels.

The VGL Transport is largely a deprecated feature.  It works well on Mac and Linux clients but is a PITA to set up on Windows clients due to the Cygwin requirement (Cygwin is the only open source Windows X server that supports MIT-SHM, which is necessary to achieve decent performance with the VirtualGL Client.)  Furthermore, only Linux X servers have the necessary extensions to support your application in the first place (Cygwin/X and XQuartz render it as opaque, irrespective of whether VirtualGL is used.)  Also, given that the VGL Transport only performs well on high-speed networks, its usefulness in the modern era of cloud computing is limited.  Most VirtualGL users these days use VGL with TurboVNC or another X proxy-- which, as you discovered, properly handles alpha channel information.  Thus, the odds that this will be fixed are pretty slim.  

Xpra has matured to the point that it is a viable substitute for the VGL Transport, for those wishing to use VirtualGL with individual applications rather than a remote desktop environment.  Although Xpra won't perform quite as well as the VGL Transport or TurboVNC, its performance is still quite good, and it is much more feature-rich and much less limited.

**Closed by dcommander** 2020-02-13 00:35 UTC
