### ISSUE TITLE
Can't install the latest package on macOS

### ISSUE THREAD

**Issue by klochowicz** [VirtualGL/virtualgl#104] opened 2019-07-04 11:42 UTC
Hi,
I just tried to install VirtualGL on MacOS Mojave and was greeted by the following message:

```
“VirtualGL-2.6.2-1.dmg” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

Firefox downloaded this file today at 8:59 pm from sourceforge.net.
```

The previous version (2.6.1) installed just fine. Any chance of repacking it so it works?

**Comment by dcommander** [comment] 2019-07-08 18:27
A blurb on [this page](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution) suggests that the error might be because the DMG is signed but not notarized, but the 2.6.1 DMG is neither signed nor notarized.  It would be awfully stupid for Apple to enforce notarization more strictly for signed DMGs than for unsigned ones.  I am upgrading my virtual machine to 10.14.5 and will re-test.

**Comment by dcommander** [comment] 2019-07-08 20:03
Confirmed that the problem exists after upgrading from 10.14.4 to 10.14.5.  I'll see what I can do.

**Comment by dcommander** [comment] 2019-07-11 23:34
As a temporary workaround, you can hold down Ctrl while right-clicking the DMG file and selecting "Open" from the context menu.  That will enable an "Open" button in the warning dialog, thus allowing you to bypass the notarization requirement until I can fix it.

**Comment by dcommander** [comment] 2019-07-12 00:52
I looked into notarizing the package, and it's such an incredible PAIN IN THE @$$.  I tried to do the right thing by signing the software with a code signing certificate, and now Apple is punishing me for that.  They want me to:

- Enable hardened runtime in all of my binaries, which is a significant undertaking
- Submit the software to their servers to be "notarized" (which basically just ensures that it doesn't have malware-- but SourceForge already scans for that)
- Use XCode 10 to build the software (but I can't actually do that because of backward compatibility issues)

Unfortunately, submitting the software to Apple's servers for notarization isn't a real-time thing.  You have to submit it and then wait for them to approve it, which may take as much as an hour.  As you can imagine, that isn't conducive to integration with a script-based build/packaging system such as ours.

Given the observed behavior of 10.14.5:
- Gatekeeper is going to complain about the .pkg regardless of whether it's signed.  It complains about the 2.6.1 .pkg being unsigned, and it complains just as hard about the 2.6.2 .pkg being un-notarized.  Conclusion: no advantage to signing the package under 10.14.5.
- Gatekeeper complains about the signed 2.6.2 DMG being un-notarized, but it doesn't complain about the unsigned 2.6.1 DMG at all.  Conclusion: no advantage-- and, in fact, a disadvantage-- to signing the DMG under 10.14.5.

Apple's stupid zero-sum game makes it so that, unless you jump through every single one of their hoops (with no guarantee that they won't create new hoops-- even in a BUG FIX version of macOS), you might as well not jump through any of them.  There is an advantage to signing the packages for 10.14.4 and prior, so I will continue to do so for the time being.  However, in the long term, if macOS is going to treat un-notarized software the same as unsigned, I might as well not bother to sign my software.  Apple has effectively created a dis-incentive to do the right thing, not an incentive.  Are you listening, Apple?  Because you're being stupid and evil and discriminatory toward the open source community.  Please stop.  Now.

With macOS 10.15, they are forcing our hand by refusing to allow any un-notarized software at all. My fear is that the Ctrl workaround for bypassing Gatekeeper may go away, which would be devastating for open source developers on Mac platforms (very few open source developers even bother to sign their applications/packages on Mac, because it costs $100/year, and the certificates-- despite being timestamped-- are still treated as unsigned by Gatekeeper once they expire.)

I'm not sure what to do about this, honestly.  At the moment, the workaround above is my only solution.

**Comment by dcommander** [comment] 2019-07-17 18:07
Can't even run altool from Xcode 10, unfortunately, since I am still building on macOS 10.12 "Sierra" for backward compatibility reasons.  Closing as WNF for now but will revisit later, in hopes that Apple streamlines the notarization process in the meantime.  For now, it will be necessary for users of 10.14.5 to Ctrl-click on the DMG to install it.  If anyone reading this has installed 10.15 beta and has any insight as to whether the Ctrl-click workaround still works, please add a comment here.

**Closed by dcommander** 2019-07-17 18:07 UTC
Labels: bug
