### ISSUE TITLE
Both of Firefox and Chrome fail to recognize hardware acceleration

### ISSUE THREAD

**Issue by masashi-sato-flect** [VirtualGL/virtualgl#186] opened 2021-12-25 04:35 UTC
Hi. I found the both of major browsers could not recognize hardware acceleration of WebGL with the latest(at this time of writing) combination of the following:
- Google Cloud Compute Engine instance with a NVIDIA T4 GPU
- Latest NVIDIA driver(v470)
- Ubuntu 20.04 LTS with apt packages of LXDE, lightdm and TigerVNC
- VirtualGL 3.0.0

In this combination, glxgears works well. With VGL_LOGO=1, I can see spinning gears with "VGL" logo.
But if I check Chrome (chrome://gpu) and Firefox(about:support), the both have fallen back to Mesa emulation.

In the case of Chrome, it outputs console error of "invalid visual id".

Do anybody advise to me how can I investigate for this problem?

**Comment by dcommander** [comment] 2021-12-25 04:39
Chrome will definitely require the dev/3.0 evolving pre-release build, since it uses EGL rather than GLX. Firefox may as well, since I heard it was also moving to EGL. See VirtualGL.org for a link to the pre-release build.

**Comment by masashi-sato-flect** [comment] 2021-12-25 04:41
Surprising quick response! Thanks I'll check it.

**Comment by masashi-sato-flect** [comment] 2021-12-25 07:54
Oh, relatedm
https://github.com/VirtualGL/virtualgl/issues/177

**Comment by masashi-sato-flect** [comment] 2021-12-27 00:50
In the case of Firefox I could work around with:

```
about:config gfx.x11-egl.force-disabled = true
```

**Comment by dcommander** [comment] 2021-12-27 01:06
Did the new EGL/X11 front end in the 3.1 evolving build also work with Firefox? If not, then I need to investigate why.

**Comment by masashi-sato-flect** [comment] 2021-12-27 01:29
No. Firefox Linux 95.0.1 (gfx.x11-egl.force-disabled = false) failed with VirtualGL 3.0.80.
about:support WebGL 1 shows the following error message.

```
WebGL 1 Driver Renderer	WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)
```

**Comment by masashi-sato-flect** [comment] 2021-12-27 01:45
In the case of Chrome, I couldn't find any work around. 
None of following worked:
- export VGL_DEFAULTFBCONFIG=GLX_ALPHA_SIZE,8,GLX_STENCIL_SIZE,8
- export VGL_FORCEALPHA=1
- --disable-seccomp-filter-sandbox
- --use-gl=desktop

**Comment by dcommander** [comment] 2021-12-27 03:02
Chrome should work with the 3.1 evolving release if you run it with the command line listed here:
https://github.com/VirtualGL/virtualgl/issues/177#issuecomment-993009808

Did you try that?

**Comment by masashi-sato-flect** [comment] 2021-12-27 03:16
I think I did it.
Actually I ran Chrome via LXDE (xstartup => vglrun -c proxy -d :0 startlxde). 
Although I didn't run vglrun with Chrome explicitly, I typed in LXDE terminal window with "google-chrome-stable --disable-seccomp-filter-sandbox" and the launched Chrome didn't recognize hardware acceleration.
I think VGL hook applied as expected.

**Comment by dcommander** [comment] 2021-12-27 03:51
Ah, yes. Chrome requires the EGL back end. The `-d :0` argument enables the GLX back end.

**Comment by dcommander** [comment] 2022-01-07 19:18
For me at least, the suggested workaround for Firefox (setting `VGL_FORCEALPHA=1` and `gfx.x11-egl.force-disabled=true`) didn't do anything, but I'm also running 91.3.0esr in CentOS 7, not 95.x.x.  I'm still investigating the issue.

**Comment by dcommander** [comment] 2022-01-07 19:43
Never mind.  The comment above was the result of testing with VGL 3.0.x, which doesn't interpose EGL/X11.  Apparently Firefox uses EGL/X11 to detect the GPU type (irrespective of the value of `gfx.x11-egl.force-disabled`), and since EGL/X11 was being passed through to the 2D X server (TurboVNC in my case), Firefox detected the llvmpipe driver and disabled hardware acceleration.  When I run Firefox 91.3.0esr using the evolving VGL 3.1 build with the EGL back end enabled (`-d egl`), everything works fine.  All of the fields under "Decision Log" show the same hardware enablement as when I run the browser on the local display without VGL.  I will test the latest Firefox version next.

**Comment by dcommander** [comment] 2022-01-07 22:32
I tested four different versions of Firefox on my system (CentOS 7.9.2009 with a Quadro K5000 and nVidia driver version 470.86.)  68.X.X and 78.X.X do not enable hardware acceleration at all, even on the local display, and the "about:support" info is identical with VirtualGL + TurboVNC vs. the local display.  91.X.X and 95.X.X behave as described above.  The "about:support" info is identical with VGL 3.1.x evolving/EGL back end + TurboVNC vs. the local display, and the VGL logo appears as expected when running WebGL applications.  With VGL 3.0.x + TurboVNC, the GPU is detected as llvmpipe, and hardware acceleration is disabled.  With VGL 3.1.x evolving/GLX back end + TurboVNC, GPU detection fails entirely, and WebGL won't work at all.

If you are unable to make Firefox 95.X.X work with the evolving VirtualGL 3.1.x pre-release build and `-d egl`, then I cannot reproduce that issue unfortunately.

**Comment by dcommander** [comment] 2022-01-10 20:09
@masashi-sato-flect Can you confirm whether hardware acceleration in Firefox works if you explicitly launch Firefox using `vglrun -d egl` and the VirtualGL 3.1.x pre-release build?  I need to know whether there is still an issue here.

**Comment by dcommander** [comment] 2022-01-13 17:35
Closing due to lack of response from the original poster.  I have updated the VirtualGL 3.1 User's Guide to indicate that the EGL back end is required for both Firefox and Chrome.  VirtualGL users who need hardware acceleration with either browser will have to use the VGL 3.1 pre-release for the time being.  I cannot reproduce any issues other than that.

**Closed by dcommander** 2022-01-13 17:35 UTC

**Comment by dcommander** [comment] 2023-03-07 21:34
For anyone stumbling upon this issue, https://github.com/VirtualGL/virtualgl/issues/228#issuecomment-1458759288 describes the results of my testing with various Firefox releases and the latest Chrome/Chromium releases using VirtualGL 3.0.2 and 3.1 post-beta.  tl;dr: VirtualGL 3.1 (which is currently in beta) and EGL/X11 are necessary in order to enable GPU acceleration with any recent versions of Chrome/Chromium, and you must use the exact application recipe listed in the VirtualGL 3.1 User's Guide.  Recent versions of Firefox should "just work", but setting `MOZ_DISABLE_CONTENT_SANDBOX=1` is necessary when using Firefox v93 and earlier with the GLX back end.
