### ISSUE TITLE
RuntimeError: Error in dlopen

### ISSUE THREAD

**Issue by abastola0** [VirtualGL/virtualgl#250] opened 2024-04-30 00:38 UTC
I faced this issue while running pytorch application but some similar issues were mentioned for julia as well (referenced here: #https://github.com/JuliaLang/julia/issues/49246)

RuntimeError: Error in dlopen: libtorch_cuda_linalg.so: cannot open shared object file: No such file or directory

Here is the debug output: 

```
     36333:	file=libtorch_cuda_linalg.so [0];  dynamically loaded by /lib/libdlfaker.so [0]
     36333:	find library=libtorch_cuda_linalg.so [0]; searching
     36333:	 search path=/home/abastol/modules/anaconda3/envs/newsn/bin/../lib		(RPATH from file python)
     36333:	  trying file=/home/abastol/modules/anaconda3/envs/newsn/bin/../lib/libtorch_cuda_linalg.so
     36333:	 search cache=/etc/ld.so.cache
     36333:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
     36333:	  trying file=/lib/x86_64-linux-gnu/libtorch_cuda_linalg.so
     36333:	  trying file=/usr/lib/x86_64-linux-gnu/libtorch_cuda_linalg.so
     36333:	  trying file=/lib/libtorch_cuda_linalg.so
     36333:	  trying file=/usr/lib/libtorch_cuda_linalg.so
     36333:	
Traceback (most recent call last):
  File "/home/abastol/working/currentAnomalyDetection/src/test.py", line 16, in <module>

```

The first hit was correct (trying file=home/abastol/modules/anaconda3/envs/newsn/bin/../lib/libtorch_cuda_linalg.so) but the not sure about the second one. There were two windows opened so not sure if the second hit (trying file=/usr/lib/libtorch_cuda_linalg.so)was for that (some concurrency issue perhaps). 

Anyway a manual export to the conda env library path seems to fix this issue (referenced here:#https://github.com/JuliaLang/julia/issues/49246) but this might be temporary.

**Comment by dcommander** [comment] 2024-05-02 20:26
I believe this is a duplicate of #107.  If so, it is a known issue, and the workaround is documented in the VirtualGL User's Guide.  (The workaround is just a convenience option to `vglrun` that does exactly what you describe: adding the application's library directory to `LD_LIBRARY_PATH`.  Refer to #107 and the VirtualGL User's Guide for an explanation of why that is necessary.)

**Closed by dcommander** 2024-05-02 20:26 UTC
Labels: duplicate
