### ISSUE TITLE
Crash of Matlab R2018a after repetitive creating/closing of figures, VirtualGL 2.6 and Debian linux 4.9 (Stretch)

### ISSUE THREAD

**Issue by jacques2020** [VirtualGL/virtualgl#77] opened 2018-08-29 05:42 UTC
Hello,

I supplement my message referred below using a different config (and having a different issue): 
https://github.com/VirtualGL/virtualgl/issues/76

I tried to run matlab 2018a with VirtualGL 2.6 under Debian Stretch. I have 2 titans black to run CUDA accelerated code but the Xorg process (LightDm) runs on a Quadro K600. No computation are run on that latter one. The driver is version 390.77 from the official debian repository. When running matlab with ```vglrun matlab -nosoftwareopengl``` bench runs smoothly, but repetitive creating and closing of figures lead to a crash. More precisely, I used the code
```
clc; clear all; close all;
for ii = 1:200
ii
f1 = ezplot('cos(x)');
saveas(f1,'testplot','fig')
print('testplot','-dbmp16m')
close all;
end
```
and after a few iterations, matlab crashed. 
I attached the
[matlab_vgl_oracleJava.log](https://github.com/VirtualGL/virtualgl/files/2330842/matlab_vgl_oracleJava.log)
for this case using the +tr option of vglrun

Because the last lines reported issues about java, I attempted to use OpenJDK 8 (1.8.0_181) by setting the corresponding environment variable. 
```
export MATLAB_JAVA="/usr/lib/jvm/java-8-openjdk-amd64/jre"
```
It crashes again although not saying the same. 
I attach the corresponding log, 
[matlab_vgl_openjdk.log](https://github.com/VirtualGL/virtualgl/files/2330845/matlab_vgl_openjdk.log)

As a control I ran matlab without VirtualGL and using the sofwatreopengl (so basically only using ```matlab``` at the command line. It ran smoothly for 1000 iterations of the above test and did not crash. Thus, openJDK on its own was not the issue.
This is a long-lived bug, still present with older versions of matlab (at least 2017a and b, and older versions of the nvidia driver).

Thank you so much for your help investigating this bug.

Best regards

Jacques

**Comment by dcommander** [comment] 2018-08-31 00:01
Does it crash both with and without `-nosoftwareopengl` when VirtualGL is not used?

**Comment by dcommander** [comment] 2018-09-06 14:49
Given that the problem is reproducible without VirtualGL, closing as SEP.

**Closed by dcommander** 2018-09-06 14:49 UTC
