### ISSUE TITLE
Problem with GLFW application: catching WM_DELETE_WINDOW

### ISSUE THREAD

**Issue by Cody-G** [VirtualGL/virtualgl#47] opened 2017-04-10 20:32 UTC
Thanks for all of your great work on this tool!

We receive this error message from VirtualGL when we close a window created by GLFW:
```
> [VGL] ERROR: in getGLXDrawable--
> [VGL]    186: Window has been deleted by window manager
```

This seems to come up pretty often as I search around the web, and I'm aware of the recommendation [here](https://sourceforge.net/p/virtualgl/mailman/message/33672284/) to intercept the `WM_DELETE_WINDOW` signal from X11.  My understanding is that VirtualGL watches that signal, and that the error is thrown whenever [this](https://github.com/VirtualGL/virtualgl/blob/262e077ed9f21ebb3176e556b32821c7f8400c9c/server/faker-x11.cpp#L575) line gets executed.  So we want to "intercept" the signal in our code, which means that we will get the signal and prevent VirtualGL from getting it.

I've looked around for examples of how to intercept the signal, and there are several ([here](https://john.nachtimwald.com/2009/11/01/x11-intercept-window-close-event/) is one).  However since our application uses GLFW and GLFW appears to do the interception [here](https://github.com/glfw/glfw/blob/72d58d7b9318199a26ac01bb3040834bb10e3d07/src/x11_init.c#L639-L640) and [here](https://github.com/glfw/glfw/blob/4ff66a7818e3eaa5362c828a18220b12f1cd9bc8/src/x11_window.c#L1292-L1297) I assumed that we would be safe in cleaning up the window using GLFW's ability to set a window close callback function which gets executed when the `WM_DELETE_WINDOW` signal is received [here](https://github.com/glfw/glfw/blob/1982543cd2943151ab538ccb31ee48cd857ab2d3/src/window.c#L103-L109).  However what's happening in our application is that both VirtualGL and GLFW are getting the signal at the same time, so by the time GLFW gets the signal it's already too late to stop the error.  It seems that GLFW is sharing rather than intercepting the signal.  I confess that I have no X11 programming experience so I may be misunderstanding how interception works.  I would like to know if this is the intended behavior of VirtualGL and GLFW (which I can also ask the GLFW developers if necessary), and how to best implement this in our application.  Thanks for any insights!

**Comment by dcommander** [comment] 2017-04-12 01:14
Yes, that error message basically means one of two things:

1. VirtualGL detected a `WM_DELETE_WINDOW` message that wasn't handled by the application, or
2. The application handled the `WM_DELETE_WINDOW` message but didn't subsequently shut down its event queue

Situation 2 seems to be what's happening in GLFW, and the same situation can be reproduced in GLXspheres by patching it thusly:

```
--- a/glxdemos/glxspheres.c
+++ b/glxdemos/glxspheres.c
@@ -423,11 +423,12 @@ int display(int advance)
 
 
 Atom protoAtom=0, deleteAtom=0;
+int shouldExit=0;
 
 
 int eventLoop(Display *dpy)
 {
-       while (1)
+       while (!shouldExit)
        {
                int advance=0, doDisplay=0;
 
@@ -466,7 +467,7 @@ int eventLoop(Display *dpy)
                                {
                                        XClientMessageEvent *cme=(XClientMessageEvent *)&event;
                                        if(cme->message_type==protoAtom && cme->data.l[0]==deleteAtom)
-                                               return 0;
+                                               shouldExit=1;
                                }
                        }
                        if(interactive)
```

The reason why VirtualGL traps `WM_DELETE_WINDOW` messages is to avoid a situation in which the window is closed by an external process (the window manager) while VirtualGL is still trying to draw to it, which would produce a BadDrawable X11 error.  Since VirtualGL is monitoring the application's X11 event queue by way of interposing `XNextEvent()` and similar functions, VGL is notified of the `WM_DELETE_WINDOW` message before the application is.  VGL sets a flag in the VirtualWin instance corresponding to the window that says, "The window manager has closed this window.  If the application tries to do anything else with the window, throw an error."  Assuming the application is also monitoring `WM_DELETE_WINDOW` messages, then the application is subsequently notified of the message.  VirtualGL currently expects that the application will shut down its event queue as soon as it is notified of the message.  However, it seems that this might be overly strict.  The aforementioned BadDrawable error will only occur if neither VirtualGL nor the application has elected to receive the `WM_DELETE_WINDOW` message.  In that case, the window manager will proceed with closing the window, but if the application has elected to receive `WM_DELETE_WINDOW` messages, then the WM assumes that the application will take care of closing the window on its own.  Therefore, I think the appropriate solution is for VirtualGL to ignore `WM_DELETE_WINDOW` messages if it detects that the application has elected to receive them.

**Closed** 2017-04-12 01:54 UTC

**Comment by dcommander** [comment] 2017-04-12 02:01
New pre-release build now available with this fix.  Please test.

http://www.virtualgl.org/DeveloperInfo/PreReleases

**Comment by Cody-G** [comment] 2017-04-12 16:25
Thanks for your thorough explanation, this is more clear to me now!  I tested the new build with the fix and our problem is solved.  Thanks!
