### ISSUE TITLE
Readback not always RenderMode safe

### ISSUE THREAD

**Issue by nathankidd** [VirtualGL/virtualgl#41] opened 2017-02-03 02:10 UTC
Consider the following X11 sequence

    10959: [73120:0] (5) --> Request 143.107 RenderMode (GLX)
    context tag       1
    mode              GL_SELECT
    10963: [73123:0] (5) <-- Reply to Request 143.107 RenderMode (GLX)
    sequence #        0xb9b (10959)
    return value      0
    n                 0
    new mode          GL_SELECT
    10967: [73124:0] (5) --> Request 143.11 glXSwapBuffers (GLX)
    context           1
    drawable          0x80008f

https://www.opengl.org/sdk/docs/man2/xhtml/glXMakeCurrent.xml says

>          GLXBadContextState is also generated if the rendering context current
>          to the calling thread has GL renderer state GLX_FEEDBACK or
>          GLX_SELECT.
        
`doGLReadback()` has a `if(renderMode!=GL_RENDER) return;` check
but `glXSwapBuffers()` jumps right into readback,  uses TempContext and gets

    X Error of failed request: GLXBadContextState
    Opcode of failed request:          155.26
    Resource id in failed request:     0x1600009
    Sequence number of failed request: 0x0
    Current serial number:             0x16e
    [VGL] ERROR: in TempContext--
    [VGL]    52: Could not bind OpenGL context to window (window may have disappeared)
    
    X Error of failed request: GLXBadContextState
    Opcode of failed request:          155.5
    Resource id in failed request:     0x1600009
    Sequence number of failed request: 0x0
    Current serial number:             0x176

**Comment by dcommander** [comment] 2017-02-03 02:40
How would one go about reproducing this?  Does it occur in a specific application?

**Comment by nathankidd** [comment] 2017-02-03 14:49
Insert a `glRenderMode(GL_SELECT)` before `glXSwapBuffers` in e.g. glxdemo.c.  This will show the two `GLXBadContextState` errors. (For reasons I'm not entirely sure of, the TempContext note does *not* get printed.)

I reproduced originally by playing back a (430MB) trace of another company's internal application.

**Comment by dcommander** [comment] 2017-02-08 04:59
This was easily fixed, but in doing so, I started second-guessing whether the current implementation is correct for single-buffered rendering.  Currently VGL examines the render mode only within the body of `glFinish()`, `glXWaitGL()`, or (optionally) `glFlush()` and assumes that, if the render mode isn't `GL_RENDER`, it should not perform a readback.  However, what if the render mode had previously been `GL_RENDER` but was changed?  For instance, patching GLXspheres as follows:

```
--- a/glxdemos/glxspheres.c
+++ b/glxdemos/glxspheres.c
@@ -365,9 +365,9 @@ int display(int advance)
        {
                renderSpheres(GL_BACK_LEFT);  renderSpheres(GL_BACK_RIGHT);
        }
-       else renderSpheres(GL_BACK);
+       else renderSpheres(GL_FRONT);
 
-       glDrawBuffer(GL_BACK);
+       glDrawBuffer(GL_FRONT);
        if(useOverlay)
        {
                glXMakeCurrent(dpy, olWin, olCtx);
@@ -397,7 +397,9 @@ int display(int advance)
                if(olDB) glXSwapBuffers(dpy, olWin);
                glXMakeCurrent(dpy, win, ctx);
        }
-       glXSwapBuffers(dpy, win);
+       glRenderMode(GL_FEEDBACK);
+       glFinish();
+       glRenderMode(GL_RENDER);
 
        if(start>0.)
        {
```

will cause spheres to be displayed when the application is run on the local display but not when it is run using VGL.  An argument could be made that VGL should emulate the behavior of the local display, but this would entail either:

1. Always performing the readback, regardless of the render mode.  I think this is less correct than what we're currently doing, because it could lead to pixels being read back and displayed even if nothing has actually been rendered to the front buffer.

2. Monitoring the `glRenderMode()` function much like we monitor `glDrawBuffer()`, in order to check whether the front buffer is "dirty" prior to performing a front buffer readback.  This is more correct but would be a pain to implement and test.

An argument could also be made that the subset of applications this affects is so small that, as long as there are no known issues, it's best to leave things as-is.

In the case of `glXSwapBuffers()`, I think that it's correct for that function to always perform a readback, regardless of the current render mode, because it's emulating a buffer swap rather than a synchronization command.

**Comment by nathankidd** [comment] 2017-02-08 18:33
I came up with virtually the same patch the other day; agree we cannot skip swap.  The part I got hung up on was https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glRenderMode.xml

> The return value of glRenderMode is determined by the render mode at the time
> glRenderMode is called, rather than by mode. The values returned for the
> three render modes are as follows:
>         GL_RENDER
>                         0.
>         GL_SELECT
>                         The number of hit records transferred to the select buffer.
>         GL_FEEDBACK
>                         The number of values (not vertices) transferred to the feedback buffer.

I didn't test this, but it seems likely that if the program was going to use the `GL_SELECT` "number of hit records" value then TempContext calling `glRenderMode()` will reset that.   Needs testing.
If my supposition bears true, then I don't see any obvious solution.  I forget all the reasons TempContext always creates a new context; could we be more selective? But maybe SELECT_MODE itself is a reason to require it.

If we're clobbering the expected `glRenderMode()` return value then perhaps the best thing is to log a warning.  Using `SELECT_MODE`, doing SwapBuffers *and* depending on the glRenderMode return value seems an unlikely combination.

Re. your frontbuffer scenario.  I think you're right that it is rare.  I'm in favour of logging a warning if we skip a readback.  Then we can leave `glRenderMode` hooking to track a "dirty while GL_RENDER" value till we actually need it. If ever.

**Comment by dcommander** [comment] 2017-02-08 20:15
The dedicated readback context was introduced in https://github.com/VirtualGL/virtualgl/commit/42589df13cf1cf8cfca4c6dd42f9cc8526835793 and https://github.com/VirtualGL/virtualgl/commit/47a3fd9f66a229a01a888487910275e613c6706f (VGL 2.3.2).  Its main purpose is to ensure that there is always a clean state prior to performing pixel readback.  Trying to re-use the application's OpenGL context proved problematic for several reasons, including:

1. It was necessary to save and restore all of the potential OpenGL parameters that might affect readback.  This was prone to human error and wasn't very future-proof.

2. The `GL_ARB_pixel_buffer_object` extension is not available in all OpenGL profiles, so there were cases in which an application was using a profile that prevented PBO readback from working in VGL.

I suspect that the number of hit records are stored with the context, in which case this should be a non-issue, but I'll test.

**Comment by dcommander** [comment] 2017-02-08 21:49
Unfortunately your suspicions were correct.  :(  Because the call to `glRender()` occurs prior to the point at which the temporary context is established, the number of values transferred to the feedback or select buffer is swallowed by VGL and can't be recovered by the 3D application.  I can't think of anything to do other than to abort the readback entirely if the render mode is not `GL_RENDER`, but in the case of the application that triggered this issue, that could very well cause it not to display anything.

**Comment by nathankidd** [comment] 2017-02-08 21:58
A faked `glRenderMode()` could theoretically return the expected value.

**Comment by dcommander** [comment] 2017-02-08 22:37
Yeah, but far from the ugliest thing about VGL.  It does seem as if this is going to require a fake `glRenderMode()` function regardless.  Blerg.

**Comment by dcommander** [comment] 2017-02-09 20:07
Vis-a-vis the front buffer rendering issue:

In my comment above, I proposed interposing `glRenderMode()` to figure out whether the front buffer is "dirty" and, thus, whether it should be sent when a synchronization function (`glFinish()`, `glFlush()`, `glXWaitGL()`) is called while the render mode is something other than `GL_RENDER`.  Upon further reflection, this is problematic.  Because of the restrictions in `glXMake[Context]Current()`, whenever a new context is swapped in, it will always start with a render mode of `GL_RENDER`.  The problem is that we can't actually know whether any rendering has occurred between the point at which the context is swapped in and the point at which `glRenderMode()` is called to change the render mode to `GL_FEEDBACK` or `GL_SELECT`.  I modified GLXspheres so that it renders to the front buffer with the render mode set to `GL_RENDER`, then changes the render mode to `GL_FEEDBACK` prior to calling `glFinish()` or `glFlush()`.  I also instrumented the code so that it requires a keypress before proceeding to the next step.  Interestingly, this revealed that, on the local display, the pixels rendered with `GL_RENDER` do not get displayed until `glFinish()` or `glFlush()` is called, even if the render mode is not `GL_RENDER` when one of those functions is called.  I guess this makes sense, given the `glFinish()` is supposed to block "until the effects of all previously called GL commands are complete", and `glFlush()` is more or less an asynchronous `glFinish()`.

I still think that it's probably best to leave things the way they are with respect to front buffer rendering, but I wanted to at least document my findings, in case this issue pops up with other applications.  The original fix (https://github.com/VirtualGL/virtualgl/commit/7125022f3dd831fc0d5b6dc72e8707709379fd42) was based on an issue Santos reported with a specific application (TrapTester.)  I wouldn't feel comfortable changing the behavior without either engaging them to re-test that specific application or providing a new environment variable that optionally reverts to the old behavior.  Not worth it until/unless another application emerges that does the same thing (switches the rendering mode while doing front buffer rendering.)

Will proceed with attempting to fix the back buffer issue by interposing `glRenderMode()`.

**Comment by dcommander** [comment] 2017-02-10 01:14
Unfortunately this is proving much nastier than anticipated.  It's not just the number of records/values transferred that is reset when calling `glRenderMode(GL_RENDER)`.  The current position in the select/feedback buffer is also reset.  :(  Consider the following:

```
GLfloat values[6] = { 0, 0, 0, 0, 0, 0 };
glFeedbackBuffer(6, GL_3D, values);
glRenderMode(GL_FEEDBACK);
glPassThrough(1.0);
glPassThrough(2.0);
glXSwapBuffers(dpy, drawable);
glPassThrough(3.0);
numTransferred=glRenderMode(GL_RENDER);
```

Ideally `numTransferred` should be 6, and the `values` array should be { 1792.0, 1.0, 1792.0, 2.0, 1792.0, 3.0 }.  With my most recent modification (not yet checked in), `numTransferred` is set correctly, but the `values` array is { 1792.0, 3.0, 1792.0, 2.0, 0.0, 0.0 }.  OpenGL apparently maintains an internal pointer to the "current" position in the select/feedback array, and there is no way to manually set that pointer.  It is reset to 0 when the render mode changes.  Maintaining our own internal feedback/select buffer wouldn't work, because the application is free to query the buffer contents at any time, and those contents are modified immediately as primitives are rendered in select mode or feedback mode.

I cannot conceive of any reasonable way to fix this without violating the OpenGL spec somehow.  It might be necessary for us to limit the scope of this fix to only the application that the issue is known to affect.  That may entail reusing the rendering context for performing readback, if a situation is encountered whereby the application calls `glXSwapBuffers()` with a render mode != `GL_RENDER`.  In and of itself, that would be a nasty fix, because it would require re-introducing very old and potentially error-prone code that attempts to store/restore the OpenGL state before and after the readback.

Since this is a company's internal application, why can't they just modify their application to do the right thing?  If it were a commercial application that has already been released into the wild, that would be a different story, but it doesn't make sense to introduce a hackish and potentially destabilizing modification to VGL to support an internal application.  By policy, I would charge a higher hourly rate for that kind of work anyhow, since the modification would benefit only that company and not the broader VGL community.

**Comment by nathankidd** [comment] 2017-02-10 02:02
On 09/02/17 08:14 PM, DRC wrote:
> Unfortunately this is proving much nastier than anticipated. It's
> not just the number of records/values transferred that is reset when
> calling |glRenderMode(GL_RENDER)|. The current position in the
> select/feedback buffer is also reset. :( Consider the following:
> 
> GLfloat values[6] = { 0, 0, 0, 0, 0, 0 }; glFeedbackBuffer(6, GL_3D,
> values); glRenderMode(GL_FEEDBACK); glPassThrough(1.0); 
> glPassThrough(2.0); glXSwapBuffers(dpy, drawable); 
> glPassThrough(3.0); numTransferred=glRenderMode(GL_RENDER);

Ugh.

> I cannot conceive of any reasonable way to fix this without
> violating the OpenGL spec somehow. It might be necessary for us to
> limit the scope of this fix to only the application that the issue is
> known to affect. That may entail reusing the rendering context for
> performing readback, if a situation is encountered whereby the
> application calls |glXSwapBuffers()| with a render mode !=
> |GL_RENDER|. In and of itself, that would be a nasty fix, because it
> would require re-introducing very old and potentially error-prone
> code that attempts to store/restore the OpenGL state before and after
> the readback.
> 
> Since this is a company's internal application, why can't they just 
> modify their application to do the right thing? If it were a
> commercial application that has already been released into the wild,
> that would be a different story, but it doesn't make sense to
> introduce a hackish and potentially destabilizing modification to VGL
> to support an internal application. By policy, I would charge a higher hourly
> rate for that kind of work anyhow, since the modification would benefit only
> that company and not the broader VGL community.

When you say "do the right thing" do you see a violation of the OpenGL
spec, or just non-standard behaviour?  I only see the latter so far,
which means even if nobody else has hit the issue yet, it *could* affect
anyone, so there is some potential community benefit.

That said, I'll examine the trace in more detail tomorrow to see if I
can determine what may be a safe workaround; I'm all for avoiding
VGL_READBACKCTX=0 as the next guy, if possible.

**Comment by dcommander** [comment] 2017-02-10 03:00
By "do the right thing", I mean "stop being weird."  However, you are correct that the behavior in question doesn't technically seem to be a violation of the spec.

As far as this potentially benefiting other applications, that argument only holds water if we are able to solve the issue in a way that doesn't introduce a compatibility minefield, and currently I can't think of a way to do that.  The best solution I can think of at the moment is to avoid the temporary context entirely if `glXSwapBuffers()` is called with render mode != `GL_RENDER`, but that would have the following stipulations:

* There is a possibility that certain parts of the OpenGL state-- specifically, those parts that can't be stored with `glPushAttrib()`/`glPushClientAttrib()`-- will be affected by VirtualGL's pixel readback function.  It isn't possible to store/restore the entire OpenGL state, which is why the temporary context mechanism was introduced.

* (more importantly) If the application has set the "read" drawable to something other than the "write" drawable (using, for instance, the GLX 1.3 `glXMakeContextCurrent()` function), then VirtualGL simply won't function properly.

Nutshell: I *might* be able to fix this *if* the application never modifies the read drawable independently of the write drawable, and if the application doesn't do anything exotic with the state, but another application could still break VGL by doing one of those things in addition to calling `glXSwapBuffers()` with render mode != `GL_RENDER`.  That's what I meant by limiting the scope of the fix.  I can't currently conceive of a way to fix this that fully conforms to the OpenGL/GLX spec.  That could potentially create more problems for the community than it solves.  Currently, if someone is writing an application that leaves the render mode set to something other than `GL_RENDER` while calling `glXSwapBuffers()`, VGL will simply crash, and that is easy for them to debug.  If I implemented the fix described above, then an application might simply fail to display properly in VGL, without producing any errors.

**Comment by dcommander** [comment] 2017-02-10 03:01
So, yeah, I'm afraid that unless we can divine a way to fix this that fully conforms, the fix will likely have to be guarded by an environment variable-- perhaps even an undocumented one.

**Comment by nathankidd** [comment] 2017-02-10 15:21
On 09/02/17 10:01 PM, DRC wrote:
> That could potentially create more problems for the community than it
> solves. Currently, if someone is writing an application that leaves
> the render mode set to something other than GL_RENDER while calling
> glXSwapBuffers(), VGL will simply crash, and that is easy for them to
> debug. If I implemented the fix described above, then an application
> might simply fail to display properly in VGL, without producing any
> errors.

I agree an explicit error is better than "sometimes works".  We could
preserve that behaviour by returning e.g. GLXBadContextState if readback
mode is PBO, or the read drawable isn't what we want.  (Are you angling
to drop non-PBO readback?)

> So, yeah, I'm afraid that unless we can divine a way to fix this
> that fully conforms, the fix will likely have to be guarded by an
> environment variable-- perhaps even an undocumented one.

Untested idea that occurred to me when I woke up this morning (those are
usually either the really good ones, or the crazy ones) :)

The current context is per-thread.  If readback was:
  1. pause render thread
  2. on separate thread do readback, TempContext shouldn't interfere
with whatever is current on the render thread
  3. unpause render thread

If that worked it could make readback far less intrusive in general.

**Comment by nathankidd** [comment] 2017-02-10 20:42
On 10/02/17 12:29 PM, DRC wrote:
> I'm not angling to drop anything. PBO readback is a critical feature.

(Angling can have a negative connotation.  I meant it in the sense of
"would you hope to some day drop non-PBO -- note *non* -- readback if
PBO availability/performance were ubiquitous"?  And thus would prefer
not to add work-arounds that depend on non-PBO readback.)

> I'll have to ponder the idea of a readback thread. Something in the
> recesses of my mind tells me that I've been down that road before, and
> there was a good reason not to do it.

I've examine my trace in more detail. For the drawable in question, "D":

 1. glXSwapBuffers(D)
 2. Other drawables made current,  D made current again, but no
rendering occurs that would dirty a buffer
 3. glXMakeCurrent(D)
 4. glRenderMode(GL_SELECT)
 5. glXRender draws, but per GL_SELECT, no framebuffer content modified
 6. glXSwapBuffers(D)
 7. glXSwapBuffers(D) (immediately again!)
 8. glFlush()
 9. glRenderMode(GL_RENDER) (returns 0)

Therefore, the swap during GL_SELECT has no effect and is safe to skip.
(Looks like  C++ constructors blindly doing their thing.)
Unfortunately I currently only have one instance of the app going to
select mode, so generalizing "always safe for this app to skip readback"
is a bit of a stretch, but I'll work on further verification.

Assuming that generalization holds, it appears to me that e.g.
VGL_SELECTREADBACK=0 is the cleanest path out?   Thoughts?

**Comment by dcommander** [comment] 2017-02-10 23:00
Sorry, I'm having difficulty parsing your comment.  If we just skipped all glXSwapBuffers() calls made when render mode != `GL_RENDER`, then would the application display anything at all?  Perhaps I'm misunderstanding your trace.  Where does a SwapBuffers call occur when render mode == `GL_RENDER`?

Not sure what you mean by the `VGL_SELECTREADBACK=0` variable.  There's no need for a variable if we're handling the case of this one application.  There is no current way to support readback with render mode == `GL_SELECT` without violating the OpenGL spec, so the choices at the moment are either to:

1. Skip readback entirely if render mode != `GL_RENDER`, or
2. Violate the OpenGL spec in a way that still works for this specific application.

It's going to be either/or, not both.  No need to introduce a new variable.

**Comment by nathankidd** [comment] 2017-02-10 23:27
On 10/02/17 06:00 PM, DRC wrote:
> Sorry, I'm having difficulty parsing your comment. If we just skipped
> all glXSwapBuffers() calls made when render mode != |GL_RENDER|, then
> would the application display anything at all? 

If we skip all glXSwapBuffers readback when render mode != GL_RENDER
then (in the one trace example I have) the application will continue to
work fine.

> Perhaps I'm misunderstanding your trace. Where does a SwapBuffers call occur when
> render mode == |GL_RENDER|?

I only paraphrased the parts from GL_SELECT to GL_RENDER, which are what
matters to determine if the glXSwapBuffers-while-GL_SELECT will have any
effect.

> Not sure what you mean by the |VGL_SELECTREADBACK=0| variable. There's
> no need for a variable if we're handling the case of this one
> application. There is no current way to support readback with render
> mode == |GL_SELECT| without violating the OpenGL spec, so the choices at
> the moment are either to:
> 
>  1. Skip readback entirely if render mode != |GL_RENDER|, or
>  2. Violate the OpenGL spec in a way that still works for this specific
>     application.
> 
> It's going to be either/or, not both. No need to introduce a new variable.

You previously mentioned leaving the default behaviour as it is now: Let
the driver return GLXBadRenderState if glXSwapBuffers is called while
render mode != GL_RENDER, so you'll know if the app is going into
uncharted territory.  I think this is sensible.   A new variable would
then be used to say "skip the readback, I acknowledge I'm going into
dangerous territory".

Did I misunderstand you and/or are you thinking of a different approach?

**Comment by dcommander** [comment] 2017-02-11 00:25
So, to be clear, in your trace above, the first glXSwapBuffers() call is made with render mode == `GL_RENDER`?

I was never proposing leaving things the way they are.  I was saying that, hypothetically, if we could not produce a solution that fully conforms to the OpenGL/GLX specs, then there are scenarios under which the fix we crafted for this specific application might cause other applications to fail in hard-to-diagnose ways.  I was mainly concerned about that possibility if the fix entailed something nasty, such as requiring that the read and write drawables be the same or disabling the temporary context.  Simply skipping the readback when glXSwapBuffers() is called with render mode != `GL_RENDER` is very similar to what we're already doing with the other synchronization functions, so that makes it pretty easy to diagnose-- if your application doesn't change the mode to `GL_RENDER`, then VirtualGL will never read back the pixels.  Simple enough.

**Comment by nathankidd** [comment] 2017-02-11 01:47
On 10/02/17 07:25 PM, DRC wrote:
> So, to be clear, in your trace above, the first glXSwapBuffers() call is
> made with render mode == |GL_RENDER|?

Yes, sorry, I should have made that explicit.  The point of including
that was to say "at this starting point there are no dirty buffers".
Thereafter the trace there is nothing that would dirty the buffers till
after GL_RENDER is restored, thus, skipping readback is safe.

> I was never proposing leaving things the way they are. I was saying
> that, hypothetically, if we could not produce a solution that fully
> conforms to the OpenGL/GLX specs, then there are scenarios under which
> the fix we crafted for this specific application might cause other
> applications to fail in hard-to-diagnose ways. I was mainly concerned
> about that possibility if the fix entailed something nasty, such as
> requiring that the read and write drawables be the same or disabling the
> temporary context. Simply skipping the readback when glXSwapBuffers() is
> called with render mode != |GL_RENDER| is very similar to what we're
> already doing with the other synchronization functions, 

If I understand you, you're suggesting to make glXSwapBuffers always
skip readback if render mode != GL_RENDER, as we already do for other
readback triggers. As far as the application I'm working with, that
would solve the issue.

> so that makes it pretty easy to diagnose-- if your application doesn't change the mode to
> |GL_RENDER|, then VirtualGL will never read back the pixels. Simple enough.

Assuming that by diagnose you mean "realize why you don't get expected
drawing results", my frequently-diagnosing self very much wants a
warning printed for any skipped readbacks (and I realize doGLReadback()
currently does not do this).  An explicit warning in a few dozen or even
hundred lines of console messages beats parsing potentially hundreds of
thousands of X requests calls to reason about whether there would be any
skipped readbacks due to render mode.

**Closed** 2017-02-13 23:14 UTC
Labels: bug

**Comment by dcommander** [comment] 2017-02-13 23:17
https://github.com/VirtualGL/virtualgl/commit/00943d329e881ed67fe21c07f8f28f9f9da126e5 implements what we talked about above-- always skipping the readback if render mode == `GL_SELECT` or `GL_FEEDBACK`; and printing a warning the first time this occurs for a particular drawable, if `VGL_VERBOSE` is 1.  I am prepared to release this as VirtualGL 2.5.2 pending the results of your testing.

**Comment by nathankidd** [comment] 2017-02-13 23:21
On 13/02/17 06:17 PM, DRC wrote:
> 00943d3
> <https://github.com/VirtualGL/virtualgl/commit/00943d329e881ed67fe21c07f8f28f9f9da126e5>
> implements what we talked about above-- always skipping the readback if
> render mode == |GL_SELECT| or |GL_FEEDBACK|; and printing a warning the
> first time this occurs for a particular drawable, if |VGL_VERBOSE| is 1.
> I am prepared to release this as VirtualGL 2.5.2 pending the results of
> your testing.

Thanks. Looks good. Will post feedback when I get it (my expectation
would be within a week or so, but it isn't in my control).

**Comment by nathankidd** [comment] 2017-03-01 19:40
Per our email conversation, I did get confirmation that the initial trigger for this issue is successfully worked around with this patch.  I did not get confirmation that every case in this application still works as expected, but that's outside the scope of this issue.
