### ISSUE TITLE
Can't compile master

### ISSUE THREAD

**Issue by svenstaro** [VirtualGL/virtualgl#109] opened 2019-11-10 11:20 UTC
I can't compile either 2.6.3 or master on Arch Linux. It breaks with:

Relevant packages I have are mesa 19.2.3, ocl-icd 2.2.12, opencl-headers 2.2.20170516, gcc 9.2.0.

```
$ cmake ..
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/cc
m-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
a-- Detecting C compiler ABI info - done
k-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
e-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- VirtualGL server components enabled (VGL_BUILDSERVER = 1)
-- CMAKE_BUILD_TYPE = Release
-- VERSION = 2.6.3, BUILD = 20191110
-- 64-bit build (x86_64)
-- CMAKE_INSTALL_PREFIX = /opt/VirtualGL
-- CMAKE_INSTALL_BINDIR = bin (/opt/VirtualGL/bin)
-- CMAKE_INSTALL_DATAROOTDIR =  (/opt/VirtualGL)
-- CMAKE_INSTALL_DOCDIR = doc (/opt/VirtualGL/doc)
-- CMAKE_INSTALL_INCLUDEDIR = include (/opt/VirtualGL/include)
-- CMAKE_INSTALL_LIBDIR = lib64 (/opt/VirtualGL/lib64)
-- Linking with static libstdc++:
   /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib/libstdc++.a
-- Performing Test INLINE_WORKS
-- Performing Test INLINE_WORKS - Success
-- INLINE = __inline__ __attribute__((always_inline)) (VGL_FORCEINLINE = 1)
-- SSL (Secure Sockets Layer) encryption disabled (VGL_USESSL = 0)
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found OpenGL: /usr/lib64/libOpenGL.so   
-- X Video support enabled (VGL_USEXV = 1)
-- TJPEG_INCLUDE_DIR = /usr/include
-- Performing Test TURBOJPEG_WORKS
-- Performing Test TURBOJPEG_WORKS - Failed
-- Could not link with official TurboJPEG library /opt/libjpeg-turbo/lib64/libturbojpeg.a.  Checking whether the operating system supplies it ...
-- Performing Test SYSTEM_TURBOJPEG_WORKS
-- Performing Test SYSTEM_TURBOJPEG_WORKS - Success
-- TJPEG_LIBRARY = turbojpeg
-- Compiler flags =  -O3 -DNDEBUG
-- Linker flags =  -L/home/svenstaro/src/virtualgl/build/staticlib -static-libgcc 
-- Using /dev/urandom for random number generation
-- Using in-tree version of FLTK
-- XCB interposer enabled (VGL_FAKEXCB = 1)
-- OpenCL interposer enabled (VGL_FAKEOPENCL = 1)
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - found
-- Found OpenCL: /usr/lib64/libOpenCL.so (found version "2.2") 
-- RPM architecture = x86_64, DEB architecture = amd64
-- Configuring done
-- Generating done
-- Build files have been written to: /home/svenstaro/src/virtualgl/build
$ make
Scanning dependencies of target vglutil
[  1%] Building CXX object util/CMakeFiles/vglutil.dir/GenericQ.cpp.o
[  1%] Building CXX object util/CMakeFiles/vglutil.dir/Log.cpp.o
[  1%] Building CXX object util/CMakeFiles/vglutil.dir/Mutex.cpp.o
[  1%] Building CXX object util/CMakeFiles/vglutil.dir/Thread.cpp.o
[  2%] Building C object util/CMakeFiles/vglutil.dir/bmp.c.o
[  2%] Building C object util/CMakeFiles/vglutil.dir/pf.c.o
[  2%] Linking CXX static library ../lib/libvglutil.a
[  2%] Built target vglutil
Scanning dependencies of target fbx
[  2%] Building C object util/CMakeFiles/fbx.dir/fbx.c.o
[  2%] Linking CXX static library ../lib/libfbx.a
[  2%] Built target fbx
Scanning dependencies of target pftest
[  3%] Building C object util/CMakeFiles/pftest.dir/pftest.c.o
[  3%] Linking CXX executable ../bin/pftest
[  3%] Built target pftest
Scanning dependencies of target vglsocket
[  3%] Building CXX object util/CMakeFiles/vglsocket.dir/Socket.cpp.o
[  3%] Linking CXX static library ../lib/libvglsocket.a
[  3%] Built target vglsocket
Scanning dependencies of target nettest
[  3%] Building CXX object util/CMakeFiles/nettest.dir/nettest.cpp.o
[  3%] Linking CXX executable ../bin/nettest
[  3%] Built target nettest
Scanning dependencies of target fbx-faker
[  4%] Building C object util/CMakeFiles/fbx-faker.dir/fbx.c.o
[  4%] Linking CXX static library ../lib/libfbx-faker.a
[  4%] Built target fbx-faker
Scanning dependencies of target bmptest
[  4%] Building C object util/CMakeFiles/bmptest.dir/bmptest.c.o
[  5%] Building C object util/CMakeFiles/bmptest.dir/md5.c.o
[  5%] Building C object util/CMakeFiles/bmptest.dir/md5hl.c.o
[  5%] Linking CXX executable ../bin/bmptest
[  5%] Built target bmptest
Scanning dependencies of target threadtest
[  5%] Building CXX object util/CMakeFiles/threadtest.dir/threadtest.cpp.o
[  5%] Linking CXX executable ../bin/threadtest
[  5%] Built target threadtest
Scanning dependencies of target fbxtest
[  5%] Building CXX object util/CMakeFiles/fbxtest.dir/fbxtest.cpp.o
[  5%] Linking CXX executable ../bin/fbxtest
[  5%] Built target fbxtest
Scanning dependencies of target fbxv
[  6%] Building C object util/CMakeFiles/fbxv.dir/fbxv.c.o
[  6%] Linking C static library ../lib/libfbxv.a
[  6%] Built target fbxv
Scanning dependencies of target glreadtest
[  7%] Building CXX object util/CMakeFiles/glreadtest.dir/glreadtest.cpp.o
[  7%] Linking CXX executable ../bin/glreadtest
[  7%] Built target glreadtest
Scanning dependencies of target fbxvtest
[  7%] Building C object util/CMakeFiles/fbxvtest.dir/fbxvtest.c.o
[  8%] Linking C executable ../bin/fbxvtest
[  8%] Built target fbxvtest
Scanning dependencies of target glframe
[  8%] Building CXX object client/CMakeFiles/glframe.dir/GLFrame.cpp.o
[  8%] Linking CXX static library ../lib/libglframe.a
[  8%] Built target glframe
Scanning dependencies of target vglcommon
[  9%] Building CXX object common/CMakeFiles/vglcommon.dir/Frame.cpp.o
[  9%] Building CXX object common/CMakeFiles/vglcommon.dir/Profiler.cpp.o
[  9%] Linking CXX static library ../lib/libvglcommon.a
[  9%] Built target vglcommon
Scanning dependencies of target frameut
[  9%] Building CXX object common/CMakeFiles/frameut.dir/frameut.cpp.o
[  9%] Linking CXX executable ../bin/frameut
[  9%] Built target frameut
Scanning dependencies of target vgltrans_test2
[ 10%] Building CXX object server/CMakeFiles/vgltrans_test2.dir/testplugin2.cpp.o
[ 10%] Building CXX object server/CMakeFiles/vgltrans_test2.dir/X11Trans.cpp.o
[ 10%] Linking CXX shared library ../lib/libvgltrans_test2.so
[ 10%] Built target vgltrans_test2
Scanning dependencies of target vgltrans_test
[ 11%] Building CXX object server/CMakeFiles/vgltrans_test.dir/testplugin.cpp.o
[ 11%] Building CXX object server/CMakeFiles/vgltrans_test.dir/VGLTrans.cpp.o
[ 11%] Linking CXX shared library ../lib/libvgltrans_test.so
[ 11%] Built target vgltrans_test
Scanning dependencies of target fakerut
[ 11%] Building CXX object server/CMakeFiles/fakerut.dir/fakerut.cpp.o
[ 11%] Building C object server/CMakeFiles/fakerut.dir/fakerut-supplement.c.o
[ 12%] Linking CXX executable ../bin/fakerut
[ 12%] Built target fakerut
Scanning dependencies of target dlfaker
[ 13%] Building C object server/CMakeFiles/dlfaker.dir/dlfaker.c.o
[ 13%] Linking C shared library ../lib/libdlfaker.so
[ 13%] Built target dlfaker
Scanning dependencies of target deepbindtest
[ 13%] Building C object server/CMakeFiles/deepbindtest.dir/libdeepbindtest.c.o
[ 13%] Linking C shared library ../lib/libdeepbindtest.so
[ 13%] Built target deepbindtest
Scanning dependencies of target gefaker
[ 13%] Building C object server/CMakeFiles/gefaker.dir/gefaker.c.o
[ 14%] Linking C shared library ../lib/libgefaker.so
[ 14%] Built target gefaker
Scanning dependencies of target dlfakerut
[ 14%] Building C object server/CMakeFiles/dlfakerut.dir/dlfakerut.c.o
[ 15%] Linking C executable ../bin/dlfakerut
[ 15%] Built target dlfakerut
[ 16%] Generating faker-mapfile
Scanning dependencies of target vglfaker-opencl
[ 16%] Building CXX object server/CMakeFiles/vglfaker-opencl.dir/ConfigHash.cpp.o
In file included from /home/svenstaro/src/virtualgl/server/glxvisual.h:18,
                 from /home/svenstaro/src/virtualgl/server/ConfigHash.h:21,
                 from /home/svenstaro/src/virtualgl/server/ConfigHash.cpp:13:
/home/svenstaro/src/virtualgl/server/faker-sym.h: In function ‘int _glXGetTransparentIndexSUN(Display*, Window, Window, long int*)’:
/home/svenstaro/src/virtualgl/server/faker-sym.h:539:46: error: comparison between distinct pointer types ‘_glXGetTransparentIndexSUNType’ {aka ‘int (*)(_XDisplay*, long unsigned int, long unsigned int, long int*)’} and ‘int (*)(Display*, Window, Window, long unsigned int*)’ {aka ‘int (*)(_XDisplay*, long unsigned int, long unsigned int, long unsigned int*)’} lacks a cast [-fpermissive]
  539 |  Window, underlay, long *, transparentIndex, glXGetTransparentIndexSUN);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/svenstaro/src/virtualgl/server/faker-sym.h:59:14: note: in definition of macro ‘CHECKSYM’
   59 |  if(__##s == fake_s) \
      |              ^~~~~~
/home/svenstaro/src/virtualgl/server/faker-sym.h:538:1: note: in expansion of macro ‘FUNCDEF4’
  538 | FUNCDEF4(int, glXGetTransparentIndexSUN, Display *, dpy, Window, overlay,
      | ^~~~~~~~
make[2]: *** [server/CMakeFiles/vglfaker-opencl.dir/build.make:67: server/CMakeFiles/vglfaker-opencl.dir/ConfigHash.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1045: server/CMakeFiles/vglfaker-opencl.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by dcommander** [comment] 2019-11-10 16:57
What Linux distribution are you using?

**Comment by svenstaro** [comment] 2019-11-10 19:24
As I've written in the issue: Arch Linux.

**Comment by davispuh** [comment] 2019-11-11 23:04
Getting exactly same issue also on ArchLinux. Looks like because of new Mesa 19.2.3.

It has `unsigned long *pTransparent`

```
glXGetTransparentIndexSUN(Display *dpy, Window overlay, Window underlay,
                          unsigned long *pTransparent)
```

See https://gitlab.freedesktop.org/mesa/mesa/commit/3dd299c3d5b88114894ec30d1fac85fba688201f

**Comment by dcommander** [comment] 2019-11-13 08:31
The problem is that this represents a backward incompatible API change in Mesa.  I can certainly appreciate the fact that they are trying to conform to the GLX extension spec, but their incorrect headers have been in the wild for so long that they're practically canonical at this point.  A simple fix in order to correct this build problem on Arch would break literally every other platform, so it will be necessary to #ifdef around this.  I am unwilling to do that until this particular version of Mesa becomes more widespread and I can see how other distros handle the backward-incompatible API change.  That means that, in all likelihood, this will need to be handled downstream (via a patch against the VirtualGL pristine source) until the newer version of Mesa makes it into Ubuntu or Fedora.  We don't officially support Arch or any other rolling distro (https://virtualgl.org/Documentation/OSSupport) for precisely this reason.  Those distros have a bad habit of unilaterally introducing backward-incompatible changes, and before I work around something like that, I want to make sure that the workaround is broadly applicable.

**Comment by svenstaro** [comment] 2019-11-13 08:57
I understand your line of thinking but please consider that this Mesa
version will become widespread sooner or later. Why not just fix it sooner
with the ifdef? I don't really see the point to delay this.

However, if you disagree, I'll certainly just downstream patch it into
Arch, no big deal.

**Comment by dcommander** [comment] 2019-11-13 18:34
VirtualGL is maintained like an enterprise product, and that's how I've been able to monetize my work on it and thus work on it (and my other open source projects) full-time for the past ten years.  Like any enterprise product, we have a list of supported platforms:
https://virtualgl.org/Documentation/OSSupport.

Arch falls under the "Community Support" category, which means that it isn't officially supported.  That means that any issue specific to Arch that can't be reproduced on one of our supported platforms probably won't be fixed unless the community fixes it or until/unless it appears on a supported platform.  The reason for that policy is primarily to preserve my sanity and to use the limited VirtualGL General Fund (the only source of sustaining funding for addressing community issues and maintaining the project) judiciously.  If I go chasing after rolling releases, I will inevitably end up working around some issue that they introduce and later fix on their own (it's happened before.)

Different distros will inevitably react in different ways to a backward-incompatible API or ABI change. (That has happened before, too, and as the maintainer of libjpeg-turbo, I witnessed it first-hand.)  The Red Hat/Fedora developers are particularly sensitive to that, so I'm mainly waiting to see how they react.  If, for instance, a distro maintainer decided to upgrade to Mesa 19.2.3 but patch out https://gitlab.freedesktop.org/mesa/mesa/commit/3dd299c3d5b88114894ec30d1fac85fba688201f, then I'd need to figure out some other way of detecting the API change besides relying on 
`GLX_GLXEXT_VERSION`.  The other issue is that VirtualGL is distributed as a cross-platform binary package, and I need to do some experiments to figure out whether (or if) a VirtualGL binary built against pre-Mesa-19.2.3 headers can work properly with an application that was built against Mesa 19.2.3.  That labor takes time, and my resources (both in terms of free time and General Fund money for addressing community issues) are constrained at the moment.

The other thing is, VirtualGL's support for `GLX_SUN_get_transparent_index` has already been removed from the evolving VGL 3.0 code base, because that extension was primarily a SPARC thing, so it doesn't make sense to fix something that isn't even going to be in the next release.  However, I still probably need to fix `glXQueryGLXPbufferSGIX()`.

**Comment by dcommander** [comment] 2019-11-13 18:41
One thing you could do to speed the process along is to test building the dev branch under Arch and verify which issues remain (since `GLX_SUN_get_transparent_index` is no longer in the dev branch.)  In all likelihood, whatever fix I implement for this will land there, not in master.

**Comment by svenstaro** [comment] 2019-11-15 11:57
That explanation makes sense.

On `dev` I get this:

```
/home/svenstaro/src/virtualgl/server/faker-glx.cpp:1814:5: error: conflicting declaration of C function ‘int glXQueryGLXPbufferSGIX(Display*, GLXPbuffer, int, unsigned int*)’
 1814 | int glXQueryGLXPbufferSGIX(Display *dpy, GLXPbuffer pbuf, int attribute,
      |     ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/GL/glx.h:333,
                 from /home/svenstaro/src/virtualgl/server/faker-sym.h:21,
                 from /home/svenstaro/src/virtualgl/server/glxvisual.h:18,
                 from /home/svenstaro/src/virtualgl/server/ContextHash.h:18,
                 from /home/svenstaro/src/virtualgl/server/faker-glx.cpp:20:
/usr/include/GL/glxext.h:852:6: note: previous declaration ‘void glXQueryGLXPbufferSGIX(Display*, GLXPbufferSGIX, int, unsigned int*)’
  852 | void glXQueryGLXPbufferSGIX (Display *dpy, GLXPbufferSGIX pbuf, int attribute, unsigned int *value);
      |      ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [server/CMakeFiles/vglfaker-opencl.dir/build.make:106: server/CMakeFiles/vglfaker-opencl.dir/faker-glx.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1045: server/CMakeFiles/vglfaker-opencl.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by svenstaro** [comment] 2019-11-15 12:35
My patch is now just:

```patch
diff --git a/server/faker-glx.cpp b/server/faker-glx.cpp
index 4a620b79..eed2b07e 100644
--- a/server/faker-glx.cpp
+++ b/server/faker-glx.cpp
@@ -1811,11 +1811,10 @@ void glXQueryDrawable(Display *dpy, GLXDrawable draw, int attribute,
 	CATCH();
 }
 
-int glXQueryGLXPbufferSGIX(Display *dpy, GLXPbuffer pbuf, int attribute,
+void glXQueryGLXPbufferSGIX(Display *dpy, GLXPbuffer pbuf, int attribute,
 	unsigned int *value)
 {
 	glXQueryDrawable(dpy, pbuf, attribute, value);
-	return 0;
 }
```

Are you planning another release in 2.x (2.6.4?) that has the `GLX_SUN_get_transparent_index` removal? I suppose you probably won't due to compatibility reasons and putting that into a patch version doesn't seem good.

**Comment by dcommander** [comment] 2019-11-15 16:04
No, given the O/S support policy I linked to above, I consider it to be a bug if VirtualGL doesn't work properly on an officially-supported platform, but supporting other platforms is an enhancement.  It is unlikely that there will be a 2.6.4 release prior to 3.0 beta, so I will revisit this prior to the beta and see where the situation stands vis-a-vis integration of Mesa 19.2.3 into other distros.  Hopefully it will be in Fedora by then, which means I can actually test it.

**Comment by dcommander** [comment] 2019-11-15 16:11
And you're correct that I wouldn't remove `GLX_SUN_get_transparent_index` from 2.6.4 even if there were a 2.6.4 release.  That extension was removed in the evolving VGL 3.0 code base because support for transparent overlay rendering was also removed.

**Comment by dcommander** [comment] 2020-01-09 02:51
Apparently this change didn't land until Mesa 19.3.0.  Not sure how you got the change with Mesa 19.2.3, unless the Arch developers back-ported it.  Thus, this will likely not be resolved from VirtualGL's point of view until Fedora 32 lands later this year.

**Comment by davispuh** [comment] 2020-02-13 00:28
That is unfortunate.

Funny thing I was about to comment on `virtualgl-git` AUR package to include @svenstaro patch so it can be built on Arch Linux but then I noticed that I am the maintainer of that package LOL. So anyway I included that patch so it can easily installed, thanks to @svenstaro!

**Comment by dcommander** [comment] 2020-02-14 01:49
It's unfortunate that people in the open source community think that it's my job to immediately drop everything I'm doing and chase down platform issues like this when doing so is of no personal benefit to me.  Our O/S support policy is clearly stated, and that policy is partly a result of rolling-release users demanding my immediate attention the second their preferred distro breaks something.  Arch is a "community support" platform.  That means that, if a VirtualGL issue exists only on that platform and you want it fixed sooner rather than later, you need to thoroughly investigate the issue, formulate a patch that fixes the issue without breaking VirtualGL on any other platform (including, BTW, Solaris and FreeBSD), and submit a PR.  Instead, you threw it over the fence to me to figure out, and if you're going to throw something over the fence to me, you're going to have to be patient, because I can't always immediately throw it back.  I have to support dozens of platforms, including some that are 10 years old but still actively deployed and receiving public updates.  In order for me to accept a patch, I have to make sure that it doesn't break VirtualGL on any of those platforms.  That takes time, and the less leg work you do on the front end, the more time it takes for me on the back end.

That being said, I downloaded the source code for Mesa 19.2.8 and 19.3.0 and was able to reproduce the issue by manipulating the `OPENGL_INCLUDE_DIR` CMake variable to point to the 19.3.0 source.  I believe that the correct fix, which I have implemented and pushed, is to adopt the newer API signatures when `GLX_GLXEXT_VERSION` is >= `20190000`.  That seems to be correct for the pristine Mesa headers.  If platforms are not using the pristine headers, then that's their problem.  I will validate the fix against Fedora 32 when it is released.

**Closed** 2020-02-14 01:49 UTC
Labels: enhancement, revisit

**Comment by svenstaro** [comment] 2020-02-14 18:43
I understand what you're saying and I'm very happy you fixed this. However, I'm not expecting anything from you and I'm not being pushy. As I said, I'm happy with downstream patches that only work for me but not for everyone as that's my use-case. I obviously do understand that you have to worry about everyone. I hope I didn't come over as pushy.

**Comment by dcommander** [comment] 2020-02-14 21:29
@svenstaro I was in a bad mood and triggered mainly on davispuh's comment ("that is unfortunate", https://github.com/VirtualGL/virtualgl/issues/109#issuecomment-585487362), which came across as critical of the fact that I was choosing to defer this issue until I could meaningfully reproduce it.  Perhaps that was a cultural disconnect, since that phrase bears a snarky connotation in the U.S.

My comment was mainly intended as a general statement to the VGL community regarding how best to approach me on issues such as these.  As an independent OSS developer who is solely in charge of three prominent projects (including the ISO reference implementation of the JPEG standard), I am pulled in about 100 different directions at any given time.  Thus, I would really appreciate it if my users would streamline the process as much as possible.  That means limiting discussions, as much as possible, to the relevant facts.  What ultimately moved me forward on this was the realization that I could test the issue using the Mesa source code without building it.  Had someone else pointed that out two months ago, the issue would have been resolved then.

**Comment by davispuh** [comment] 2020-02-14 23:33
You took this in totally wrong way, I was commenting about the situation itself that Arch users will have to wait for patch and nothing about you. Of course while people wish/want that issues would be fixed immediately it's just not realistic and everyone knows that (if someone doesn't and actually expects that to happen they need some harsh reality check). Neither you nor anyone else has any obligations to fix anything, no one is demanding that. And even if someone is, you shouldn't take it personally, it's more about them than you so just ignore/move on because you definitely have better things to do.
So anyway I understand and agree with everything you said and comments on issues doesn't mean you have to change your plans if you have more important things to do. Also I'm really grateful and thankful for all the work you do, even if I've had many issues with this software it doesn't mean it's not awesome but more that my setup is a bit too exotic 😃
